language: ruby
rvm:
 - 2.7.1
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
before_install:
  - gem update --system
  - gem install bundler