version: '3'
volumes:
  tags-api-db:
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - tags-api-db:/var/lib/postgresql/data
    ports:
      - "5436:5432"
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/tags-api
    ports:
      - "3000:3000"
    depends_on:
      - db